### ISSUE TITLE
tracked subscription needs to be tracked somewhere else in order to work

### ISSUE THREAD

**Issue by qleguennec** [vimsical/re-frame-utils#13]
Expected behavior:
When I register a track over `[:sub-a]`, I expect that that associated event is dispatched whenever any of the depedencies of `[:sub-a]` is updated.

Actual behavior:
It works when I `@(subscribe [:sub-a])` in a component.

As odd as it sounds, it seems that if I don't subscribe to `[:sub-a]` additionaly to the track, the value under `[:sub-a]` never gets updated.

**Comment by p-himik** [comment]
~~Are you sure that the relevant event is getting dispatched thanks to the sub and not via some other means? The relevant functionality does not call `dispatch` and doesn't do anything else that might lead to an event being dispatched.~~

~~And in general, coeffects are for providing data to events dispatched from somewhere. Coeffects themselves do not dispatch anything.~~

Never mind, I managed to completely misunderstand the question.

**Comment by qleguennec** [comment]
I fixed it. It turns out it was an issue with figwheel reloading. If anyone gets this issue in the future, please test it out without figwheel reloading, it may help.
