### ISSUE TITLE
Request for a non snapshot release

### ISSUE THREAD

**Issue by cldwalker** [vimsical/re-frame-utils#2]
Hi,
 We're using your helpful library in production and would like to depend on a non-snapshot release. Would you consider bumping what's currently available as a non-snapshot release or is it still too alpha?

Thanks!
Gabriel

**Comment by julienfantin** [comment]
Hi @cldwalker, 

Snapshot has been stable and we haven't gotten any bug reports, so I just released `0.1.0` to [clojars](https://clojars.org/re-frame-utils)

Best,
Julien

**Comment by cldwalker** [comment]
Pulled this into production. Thanks!
